/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    About: typeof import('./src/components/About.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    copy: typeof import('./src/components/TimeList copy.vue')['default']
    CutPage: typeof import('./src/components/CutPage.vue')['default']
    Detail: typeof import('./src/components/Detail.vue')['default']
    EditHotKey: typeof import('./src/components/setting/EditHotKey.vue')['default']
    Group: typeof import('./src/components/Group.vue')['default']
    HotKey: typeof import('./src/components/setting/HotKey.vue')['default']
    ImageItem: typeof import('./src/components/ImageItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/setting/Setting.vue')['default']
    SettingsWindow: typeof import('./src/components/SettingsWindow.vue')['default']
    TextEdit: typeof import('./src/components/TextEdit.vue')['default']
    TimeList: typeof import('./src/components/TimeList.vue')['default']
    'TimeList copy': typeof import('./src/components/TimeList copy.vue')['default']
    TimeList_back1: typeof import('./src/components/TimeList_back1.vue')['default']
    TimePage: typeof import('./src/components/TimePage.vue')['default']
  }
}
